### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ndzamboni** [ndzamboni/challenge-3#1]
- [x] App currently resets data when starting a new input after submitting (global const)
- [x] App currently "breaks" on typing 'done'. Change to window option to 'cancel' or 'ok' 
- [x] If you're feeling spicy make a dark/light mode button to keep practicing the JavaScript for that.

**Comment by ndzamboni** [comment]
did the dark mode button on landing page
i think im ok with the code "break" on typing done. maybe i'll change it tomorrow but it meets the requirements
